#!/usr/bin/env julia
#
# Emit a disBatch task file for a Hubbard-quench parameter sweep.
# ==============================================================
#
# One task per parameter point. Canopy's `apply!` is single-threaded, so the efficient shape
# on Rusty/Popeye is one *process* per point with BLAS pinned to one thread — which is exactly
# what disBatch does inside a single Slurm allocation.
#
#   ./make_sweep.jl --chi 4 8 16 32 --U 0 2 4 --symmetry trivialtrivial u1u1 \
#                   -- --lattice hex --size 6 6 --dt 0.01 --tfinal 1.0
#
# Everything after `--` is passed through to `run.jl` unchanged, so any flag it accepts can be
# held fixed across the sweep.
#
# This script only *writes* the task file and prints the suggested submission command; it
# never submits anything itself.

using Pkg
Pkg.activate(@__DIR__; io = devnull)

using ArgParse
using Printf

const RUNNER = joinpath(@__DIR__, "run.jl")
const REPO = normpath(joinpath(@__DIR__, "..", ".."))

function parse_cli(args)
    s = ArgParseSettings(
        description = "Emit a disBatch task file for a Hubbard-quench parameter sweep.",
        epilog = "Flags after `--` are forwarded verbatim to run.jl.",
        autofix_names = true,
    )
    @add_arg_table! s begin
        "--chi"
        help = "bond dimensions to sweep"
        arg_type = Int
        nargs = '+'
        default = [4, 8, 16, 32]
        "--U"
        help = "interaction strengths to sweep"
        arg_type = Float64
        nargs = '+'
        default = [0.0]
        "--symmetry"
        help = "symmetry combinations as <particle><spin>, e.g. trivialtrivial u1u1"
        nargs = '+'
        default = ["trivialtrivial"]
        "--quench"
        help = "quench protocols to sweep"
        nargs = '+'
        default = ["cdw"]
        "--outfile"
        help = "path of the generated task file"
        default = joinpath(@__DIR__, "sweep.disbatch")
        "--logdir"
        help = "directory for per-task stdout/stderr"
        default = joinpath(@__DIR__, "results", "logs")
        "--outroot"
        help = "results root handed to run.jl"
        default = joinpath(@__DIR__, "results")
        "passthrough"
        help = "extra run.jl flags (after --)"
        nargs = '*'
        default = String[]
    end
    return parse_args(args, s)
end

# "u1u1" → ("u1", "u1"); the concatenation is unambiguous because the only names are
# `trivial` and `u1`, neither of which is a prefix of the other.
function split_symmetry(name)
    for p in ("trivial", "u1"), sp in ("trivial", "u1")
        name == p * sp && return (p, sp)
    end
    error(
        "cannot parse symmetry `$name`; expected <particle><spin> built from " *
            "`trivial`/`u1`, e.g. trivialu1"
    )
end

function (@main)(args)
    o = parse_cli(args)
    mkpath(dirname(o["outfile"]))
    mkpath(o["logdir"])

    extra = String[o["outroot"] == "" ? "" : "--outroot", o["outroot"]]
    append!(extra, o["passthrough"])
    filter!(!isempty, extra)

    points = NamedTuple[]
    for q in o["quench"], sym in o["symmetry"], U in o["U"], χ in o["chi"]
        p, sp = split_symmetry(sym)
        push!(points, (; quench = q, particle = p, spin = sp, U, chi = χ))
    end

    open(o["outfile"], "w") do io
        println(io, "# Hubbard quench sweep — $(length(points)) tasks")
        println(io, "# generated by make_sweep.jl; run with disBatch inside a Slurm allocation")
        # PREFIX/SUFFIX keep the per-task lines short and put every task's output in its own
        # file. `JULIA_NUM_THREADS=1` and run.jl's `--blas-threads 1` default keep each task
        # on one core, so disBatch can pack the allocation densely.
        println(
            io,
            "#DISBATCH PREFIX cd $(REPO) && JULIA_NUM_THREADS=1 julia --project=$(dirname(RUNNER)) $(RUNNER) "
        )
        println(io, "#DISBATCH SUFFIX  > $(o["logdir"])/task_\${DISBATCH_TASKID}.log 2>&1")
        for pt in points
            println(
                io,
                join(
                    [
                        "--quench", pt.quench,
                        "--particle-symmetry", pt.particle,
                        "--spin-symmetry", pt.spin,
                        "--U", @sprintf("%g", pt.U),
                        "--chi", string(pt.chi),
                        extra...,
                    ], " "
                )
            )
        end
    end

    @printf("wrote %d tasks → %s\n", length(points), o["outfile"])
    println("  χ          : ", o["chi"])
    println("  U          : ", o["U"])
    println("  symmetries : ", o["symmetry"])
    println("  quenches   : ", o["quench"])
    println("  logs       : ", o["logdir"])
    println()
    println("Submit it yourself — this script does not run any Slurm command. For example:")
    println()
    @printf(
        "  sbatch -n %d -c 1 -t 12:00:00 --wrap 'disBatch %s'\n",
        min(length(points), 32), o["outfile"]
    )
    println()
    println("or from inside an existing allocation:  disBatch $(o["outfile"])")
    println("See https://wiki.flatironinstitute.org/SCC/Software/Slurm for the site's guidance.")
    return 0
end
