#!/usr/bin/env julia
#
# Emit a disBatch task file for a Hubbard-quench parameter sweep.
# ==============================================================
#
# One task per parameter point. Canopy's `apply!` is single-threaded, so the efficient shape
# on Rusty/Popeye is one *process* per point with BLAS pinned to one thread — which is exactly
# what disBatch does inside a single Slurm allocation.
#
#   ./make_sweep.jl --chi 4 8 16 32 --U 0 2 4 --symmetry trivialtrivial u1u1 \
#                   -- --lattice hex --size 6 6 --dt 0.01 --tfinal 1.0
#
# Everything after `--` is passed through to `run.jl` unchanged, so any flag it accepts can be
# held fixed across the sweep.
#
# This script only *writes* the task file and prints the suggested submission command; it
# never submits anything itself.

using Pkg
Pkg.activate(@__DIR__; io = devnull)

using ArgParse
using Printf

const RUNNER = joinpath(@__DIR__, "run.jl")
const REPO = normpath(joinpath(@__DIR__, "..", ".."))

function parse_cli(args)
    s = ArgParseSettings(
        description = "Emit a disBatch task file for a Hubbard-quench parameter sweep.",
        epilog = "Flags after `--` are forwarded verbatim to run.jl.",
        autofix_names = true,
    )
    @add_arg_table! s begin
        "--chi"
        help = "bond dimensions to sweep"
        arg_type = Int
        nargs = '+'
        default = [4, 8, 16, 32]
        "--U"
        help = "interaction strengths to sweep"
        arg_type = Float64
        nargs = '+'
        default = [0.0]
        "--symmetry"
        help = "symmetry combinations as <particle><spin>, e.g. trivialtrivial u1u1"
        nargs = '+'
        default = ["trivialtrivial"]
        "--quench"
        help = "quench protocols to sweep"
        nargs = '+'
        default = ["cdw"]
        "--outfile"
        help = "path of the generated task file"
        default = joinpath(@__DIR__, "sweep.disbatch")
        "--logdir"
        help = "directory for per-task stdout/stderr"
        default = joinpath(@__DIR__, "results", "logs")
        "--outroot"
        help = "results root handed to run.jl"
        default = joinpath(@__DIR__, "results")
        "--julia"
        help = "julia binary the tasks invoke. Defaults to the one running this script, by \
                absolute path — do NOT emit a bare `julia`: with juliaup installed on a \
                workstation's local disk (/home/\$USER/.juliaup) the name does not resolve on \
                compute nodes at all. Sys.BINDIR points at the real toolchain under \
                ~/.julia/juliaup on shared home, which every node can see, and is the same \
                Julia that resolved this project's Manifest."
        default = joinpath(Sys.BINDIR, "julia")
        "passthrough"
        help = "extra run.jl flags (after --)"
        nargs = '*'
        default = String[]
    end
    return parse_args(args, s)
end

# "u1u1" → ("u1", "u1"); the concatenation is unambiguous because the only names are
# `trivial` and `u1`, neither of which is a prefix of the other.
function split_symmetry(name)
    for p in ("trivial", "u1"), sp in ("trivial", "u1")
        name == p * sp && return (p, sp)
    end
    error(
        "cannot parse symmetry `$name`; expected <particle><spin> built from " *
            "`trivial`/`u1`, e.g. trivialu1"
    )
end

function (@main)(args)
    o = parse_cli(args)
    mkpath(dirname(o["outfile"]))
    mkpath(o["logdir"])
    # `--output` is expanded by Slurm at submit time, so the recommended command below points it
    # here; otherwise the job's top-level log lands in whatever directory sbatch was run from.
    mkpath(joinpath(abspath(o["outroot"]), "_run"))

    extra = String[o["outroot"] == "" ? "" : "--outroot", o["outroot"]]
    append!(extra, o["passthrough"])
    filter!(!isempty, extra)

    points = NamedTuple[]
    for q in o["quench"], sym in o["symmetry"], U in o["U"], χ in o["chi"]
        p, sp = split_symmetry(sym)
        push!(points, (; quench = q, particle = p, spin = sp, U, chi = χ))
    end

    outroot = abspath(o["outroot"])
    logdir = abspath(o["logdir"])

    open(o["outfile"], "w") do io
        println(io, "# Hubbard quench sweep — $(length(points)) tasks")
        println(io, "# generated by make_sweep.jl; run with disBatch inside a Slurm allocation")
        # Read by slurm/disbatch.sbatch so it can gather every log for a job under
        # <outroot>/_run/<jobid>/ instead of scattering them across the source tree.
        println(io, "#HQ OUTROOT $(outroot)")
        # PREFIX/SUFFIX keep the per-task lines short and put every task's output in its own
        # file. `JULIA_NUM_THREADS=1` and run.jl's `--blas-threads 1` default keep each task
        # on one core, so disBatch can pack the allocation densely.
        julia = o["julia"]
        isfile(julia) || @warn "julia binary does not exist; tasks will fail" julia
        startswith(julia, "/home/") && @warn """
            The julia path is under /home, which is node-local NVMe — compute nodes cannot see \
            it and every task will fail with `No such file or directory`. Pass --julia with a \
            path under /mnt/home.
            """ julia
        println(
            io,
            "#DISBATCH PREFIX cd $(REPO) && JULIA_NUM_THREADS=1 $(julia) --project=$(dirname(RUNNER)) $(RUNNER) "
        )
        # `HQ_TASKLOG_DIR` lets disbatch.sbatch place per-task logs under the job's own run
        # folder; the fallback keeps the task file runnable by hand outside Slurm.
        println(
            io,
            "#DISBATCH SUFFIX  > \${HQ_TASKLOG_DIR:-$(logdir)}/task_\${DISBATCH_TASKID}.log 2>&1"
        )
        for pt in points
            println(
                io,
                join(
                    [
                        "--quench", pt.quench,
                        "--particle-symmetry", pt.particle,
                        "--spin-symmetry", pt.spin,
                        "--U", @sprintf("%g", pt.U),
                        "--chi", string(pt.chi),
                        extra...,
                    ], " "
                )
            )
        end
    end

    @printf("wrote %d tasks → %s\n", length(points), o["outfile"])
    println("  χ          : ", o["chi"])
    println("  U          : ", o["U"])
    println("  symmetries : ", o["symmetry"])
    println("  quenches   : ", o["quench"])
    println("  logs       : ", o["logdir"])
    println()
    println("Submit it yourself — this script does not run any Slurm command. For example:")
    println()
    @printf(
        "  sbatch -n %d -t 4:00:00 -C icelake --mem=0 \\\n           --output=%s/_run/slurm-%%j.log \\\n           %s \\\n           %s\n",
        length(points), outroot,
        relpath(joinpath(@__DIR__, "slurm", "disbatch.sbatch")), o["outfile"]
    )
    println()
    println("  -n is the concurrent task count; -t must cover the SLOWEST SINGLE task.")
    println("  --output keeps Slurm's own log out of the submit directory; every log for the")
    println("  job then lands under $(outroot)/_run/<jobid>/.")
    println()
    println("or from inside an existing allocation:  disBatch $(o["outfile"])")
    println("See https://wiki.flatironinstitute.org/SCC/Software/Slurm for the site's guidance.")
    return 0
end
